-- ================================================================
-- FILE:     LIFE400DDL.sql
-- SYSTEM:   LIFE400 - ACME LIFE INSURANCE CO.
-- PURPOSE:  DB2-COMPATIBLE DDL EQUIVALENTS OF LIFE400 DDS FILES
--           SUPPLEMENTAL FOR SWIMM CODE ANALYSIS
--           SOURCE DDS FILES ARE IN QDDSSRC/
-- ----------------------------------------------------------------
-- PLATFORM NOTE:
--   LIFE400 RUNS ON IBM AS/400 (IBM i). DATABASE SCHEMA IS
--   NATIVELY DEFINED AS DDS PHYSICAL FILES (.pf) AND LOGICAL
--   FILES (.lf) RATHER THAN DB2 DDL. THIS FILE PROVIDES
--   EQUIVALENT CREATE TABLE/INDEX STATEMENTS SO THAT TOOLS
--   EXPECTING DB2 DDL (SUCH AS SWIMM) CAN ANALYZE THE SCHEMA.
--
-- DDS-TO-SQL TYPE MAP USED:
--   nA          -> CHAR(n)
--   nS 0        -> DECIMAL(n,0)   -- DATES STORED AS YYYYMMDD
--   nS p        -> DECIMAL(n,p)
-- ================================================================


-- ================================================================
-- TABLE: POLMST
-- SOURCE: QDDSSRC/POLMST.pf
-- DESCRIPTION: POLICY MASTER FILE - ONE RECORD PER POLICY
-- KEY: POLID (PRIMARY)
-- ================================================================
CREATE TABLE LIFE400.POLMST (
    -- CONTROL FIELDS
    POLID       CHAR(12)        NOT NULL,   -- POLICY ID
    APPID       CHAR(12)        NOT NULL,   -- APPLICATION ID
    PRCDATE     DECIMAL(8,0)    NOT NULL,   -- PROCESS DATE YYYYMMDD
    PLANCD      CHAR(5)         NOT NULL,   -- PLAN CODE
    CNTRSTS     CHAR(2)         NOT NULL,   -- CONTRACT STATUS
    ISSCHN      CHAR(2)         NOT NULL,   -- ISSUE CHANNEL
    CURCD       CHAR(3)         NOT NULL,   -- CURRENCY CODE

    -- INSURED FIELDS
    INSNAME     CHAR(40)        NOT NULL,   -- INSURED NAME
    INSDOB      DECIMAL(8,0)    NOT NULL,   -- DATE OF BIRTH YYYYMMDD
    ISSAGE      DECIMAL(3,0)    NOT NULL,   -- ISSUE AGE
    GENDER      CHAR(1)         NOT NULL,   -- GENDER M/F
    SMOKER      CHAR(1)         NOT NULL,   -- SMOKER STATUS S/N
    OCCLAS      DECIMAL(1,0)    NOT NULL,   -- OCCUPATION CLASS 1-4
    UWCLAS      CHAR(2)         NOT NULL,   -- UW CLASS PR/ST/TB/DP
    HIRAVOC     CHAR(1)         NOT NULL,   -- HIGH RISK AVOCATION Y/N
    FLTXTRA     DECIMAL(6,4)    NOT NULL,   -- FLAT EXTRA RATE PER 1000

    -- BENEFIT FIELDS
    SUMASSR     DECIMAL(15,2)   NOT NULL,   -- SUM ASSURED
    LOANBAL     DECIMAL(15,2)   NOT NULL,   -- POLICY LOAN BALANCE
    BILMODE     CHAR(1)         NOT NULL,   -- BILLING MODE A/S/Q/M

    -- PREMIUM FIELDS
    ANPREM      DECIMAL(15,2)   NOT NULL,   -- TOTAL ANNUAL PREMIUM
    MODPREM     DECIMAL(15,2)   NOT NULL,   -- MODAL PREMIUM
    OUTPREM     DECIMAL(15,2)   NOT NULL,   -- OUTSTANDING PREMIUM

    -- DATE FIELDS (ALL STORED AS YYYYMMDD - Y2K COMPLIANT)
    ISSDATE     DECIMAL(8,0)    NOT NULL,   -- ISSUE DATE YYYYMMDD
    EFFDATE     DECIMAL(8,0)    NOT NULL,   -- EFFECTIVE DATE YYYYMMDD
    PAIDTO      DECIMAL(8,0)    NOT NULL,   -- PAID TO DATE YYYYMMDD
    EXPDATE     DECIMAL(8,0)    NOT NULL,   -- EXPIRY DATE YYYYMMDD
    LSTMNT      DECIMAL(8,0)    NOT NULL,   -- LAST MAINTENANCE DATE YYYYMMDD

    -- AUDIT
    LSTUSR      CHAR(10)        NOT NULL,   -- LAST ACTION USER ID

    CONSTRAINT POLMST_PK PRIMARY KEY (POLID)
);


-- ================================================================
-- TABLE: CLMPF
-- SOURCE: QDDSSRC/CLMPF.pf
-- DESCRIPTION: CLAIMS FILE - ONE RECORD PER CLAIM
-- KEY: CLMID (PRIMARY), POLID (FOREIGN -> POLMST)
-- ================================================================
CREATE TABLE LIFE400.CLMPF (
    -- CLAIM IDENTIFICATION
    CLMID       CHAR(12)        NOT NULL,   -- CLAIM ID
    POLID       CHAR(12)        NOT NULL,   -- POLICY ID (FK -> POLMST)

    -- CLAIM DATA
    CLMTYPE     CHAR(2)         NOT NULL,   -- CLAIM TYPE (DT=DEATH)
    CAUSDTH     CHAR(3)         NOT NULL,   -- CAUSE OF DEATH
    DTHDTC      DECIMAL(8,0)    NOT NULL,   -- DATE OF DEATH YYYYMMDD

    -- DOCUMENT FLAGS
    DTHCERT     CHAR(1)         NOT NULL,   -- DEATH CERTIFICATE RECEIVED Y/N
    CLMFORM     CHAR(1)         NOT NULL,   -- CLAIM FORM RECEIVED Y/N
    IDPROOF     CHAR(1)         NOT NULL,   -- ID PROOF RECEIVED Y/N
    MEDRECS     CHAR(1)         NOT NULL,   -- MEDICAL RECORDS RECEIVED Y/N

    -- BENEFICIARY
    BENNAME     CHAR(40)        NOT NULL,   -- BENEFICIARY NAME
    BENREL      CHAR(20)        NOT NULL,   -- BENEFICIARY RELATION

    -- CLAIM STATUS AND DECISION
    CLMSTS      CHAR(1)         NOT NULL,   -- CLAIM STATUS
    CLMDEC      CHAR(1)         NOT NULL,   -- CLAIM DECISION A/R/P
    INVSTS      CHAR(1)         NOT NULL,   -- INVESTIGATION STATUS N/P/C
    CLMHOLD     CHAR(50)        NOT NULL,   -- HOLD REASON

    -- PAYMENT
    PYMTAMT     DECIMAL(15,2)   NOT NULL,   -- CLAIM PAYMENT AMOUNT
    PYMTMODE    CHAR(1)         NOT NULL,   -- PAYMENT MODE C=CHK A=ACH

    -- DATES (ALL STORED AS YYYYMMDD - Y2K COMPLIANT)
    CLMDATE     DECIMAL(8,0)    NOT NULL,   -- CLAIM SUBMIT DATE YYYYMMDD
    INVDATE     DECIMAL(8,0)    NOT NULL,   -- INVESTIGATION DATE YYYYMMDD
    ADJDATE     DECIMAL(8,0)    NOT NULL,   -- ADJUDICATION DATE YYYYMMDD
    SETDATE     DECIMAL(8,0)    NOT NULL,   -- SETTLEMENT DATE YYYYMMDD

    CONSTRAINT CLMPF_PK PRIMARY KEY (CLMID),
    CONSTRAINT CLMPF_POL_FK FOREIGN KEY (POLID)
        REFERENCES LIFE400.POLMST (POLID)
);


-- ================================================================
-- TABLE: SVCPF
-- SOURCE: QDDSSRC/SVCPF.pf
-- DESCRIPTION: SERVICE AMENDMENTS FILE - ONE RECORD PER AMENDMENT
-- KEY: SVCID (PRIMARY), POLID (FOREIGN -> POLMST)
-- AMENDMENT TYPES: PL=PLAN CHANGE, SA=SUM ASSURED, BM=BILLING MODE
--                  AR=ADD RIDER, RR=REMOVE RIDER, RI=REINSTATEMENT
-- ================================================================
CREATE TABLE LIFE400.SVCPF (
    -- AMENDMENT IDENTIFICATION
    SVCID       CHAR(12)        NOT NULL,   -- SERVICE REQUEST ID
    POLID       CHAR(12)        NOT NULL,   -- POLICY ID (FK -> POLMST)

    -- AMENDMENT DETAILS
    AMDTYPE     CHAR(2)         NOT NULL,   -- AMENDMENT TYPE PL/SA/BM/AR/RR/RI
    AMDSTS      CHAR(2)         NOT NULL,   -- AMENDMENT STATUS PE/AP/RJ
    SVCFEE      DECIMAL(9,2)    NOT NULL,   -- SERVICE FEE CHARGED

    -- PLAN CHANGE FIELDS
    OLDPLAN     CHAR(5)         NOT NULL,   -- OLD PLAN CODE
    NEWPLAN     CHAR(5)         NOT NULL,   -- NEW PLAN CODE

    -- SUM ASSURED CHANGE FIELDS
    OLDSA       DECIMAL(15,2)   NOT NULL,   -- OLD SUM ASSURED
    NEWSA       DECIMAL(15,2)   NOT NULL,   -- NEW SUM ASSURED

    -- BILLING MODE CHANGE FIELDS
    OLDBM       CHAR(1)         NOT NULL,   -- OLD BILLING MODE A/S/Q/M
    NEWBM       CHAR(1)         NOT NULL,   -- NEW BILLING MODE A/S/Q/M

    -- PREMIUM IMPACT
    NEWMODP     DECIMAL(15,2)   NOT NULL,   -- NEW MODAL PREMIUM AFTER AMENDMENT
    PREMDLT     DECIMAL(15,2)   NOT NULL,   -- PREMIUM DELTA (NEW - OLD)

    -- DATE AND AUDIT (DATE STORED AS YYYYMMDD - Y2K COMPLIANT)
    SVCDATE     DECIMAL(8,0)    NOT NULL,   -- SERVICE DATE YYYYMMDD
    USERID      CHAR(10)        NOT NULL,   -- REQUESTING USER ID

    CONSTRAINT SVCPF_PK PRIMARY KEY (SVCID),
    CONSTRAINT SVCPF_POL_FK FOREIGN KEY (POLID)
        REFERENCES LIFE400.POLMST (POLID)
);


-- ================================================================
-- INDEX: POLMSTL1
-- SOURCE: QDDSSRC/POLMSTL1.lf
-- DESCRIPTION: AS/400 LOGICAL FILE OVER POLMST KEYED BY POLID.
--   ON AS/400, ALL ONLINE AND BATCH COBOL PROGRAMS OPEN POLMSTL1
--   (NOT POLMST DIRECTLY) FOR RANDOM-ACCESS READS BY POLICY ID.
--   POLMST PRIMARY KEY ALREADY COVERS THIS ACCESS PATH; THIS INDEX
--   IS PROVIDED FOR COMPLETENESS AND SWIMM CROSS-REFERENCE.
-- ================================================================
CREATE INDEX LIFE400.POLMSTL1
    ON LIFE400.POLMST (POLID);
